Repository infotik/infotik, pull requests merged in 2024-06, with the labels that each got.

#1 v2 InfoTik - [BUGFIXES]
  .gitignore
  Main.jsx
  app.json
  assets/fb-icon.png
  assets/fb_logo2.png
  assets/google_icon.png
  assets/inapplogo.png
  eas.json
  google-services.json
  package-lock.json
  package.json
  src/components/Button.jsx
  src/components/Input.jsx
  src/components/ProfileHeader.jsx
  src/components/ReelCard.jsx
  src/components/RenderProfile.jsx
  src/components/Scroller.jsx
  src/components/SocialButton.jsx
  src/components/post/index.js
  src/components/postList/item/index.js
  src/constants/index.js
  src/redux/actions/user.js
  src/screens/Discover.jsx
  src/screens/Keyword.jsx
  src/screens/Login.jsx
  src/screens/Register.jsx
  src/screens/SavePost.jsx
  src/screens/Splash.jsx
  src/screens/userPosts.jsx
Labels: enhancement

#2 Comment Feature
  firebaseConfig.js
  src/components/post/CommentModel.jsx
  src/components/post/index.js
  src/components/post/overlay/index.js
  src/redux/actions/user.js
Labels: enhancement

#4 BugFix + Feature Change
  src/components/post/CommentModel.jsx
  src/components/post/index.js
  src/components/post/test.js
  src/redux/actions/user.js
  src/screens/Register.jsx
  src/screens/ScrollScreen.jsx
Labels: enhancement, bug-fix

#5 Improvements & Features
  src/redux/actions/user.js
  src/screens/ScrollScreen.jsx
Labels: enhancement

#6 Displaying total likes on users Profile & fixed profile image visibility…
  src/components/ProfileHeader.jsx
  src/redux/actions/user.js
Labels: bug-fix
